---
#########################################
### MOSARTWMPY Configuration Defaults ###
#########################################
### READ ONLY
### To override configuration defaults, edit config.yaml

###
### Simulation
###
simulation:
    # name this simulation
    name: mosartwmpy
    # date to begin the simulation
    start_date: 1981-01-01
    # date to end the simulation
    end_date: 1981-01-31
    # mosart timestep in seconds
    timestep: 10800
    # subcycles - subtimestep will be timestep / subcycles
    subcycles: 3
    # routing iterations - subsubtimestep will be timestep / subcycles / routing_iterations - then further subdivided within subnetwork and main channel based on convergence estimations
    routing_iterations: 5
    # routing method to use
    # TODO only 1 is implemented so far
    # 1 --> variable storage method from SWAT model; 2 --> Muskingum method?  ( 1 -- Kinematic wave method; 4 -- Diffusion wave method. --Inund. )
    routing_method: 1
    # log level, one of DEBUG, INFO, WARNING, ERROR, CRITICAL
    log_level: INFO
    # resume simulation from restart file
    # TODO not yet supported
    restart_file: ~
    # how often to write a restart file; one of 'daily', 'monthly', 'yearly' -- a restart file is also always written at the end of the simulation
    restart_file_frequency: yearly
    # output write frequency in simulation seconds; must be a multiple of simulation timestep; values will be averaged across the intervening timesteps
    # TODO only daily (86400) is currently supported
    output_resolution: 86400 # output values once each day, averaged across the timesteps
    # how often to write a new output file; one of 'daily', 'monthly', 'yearly'
    output_file_frequency: monthly
    # time dependent output fields
    output:
        - variable: hillslope_surface_runoff
          name: QSUR_LIQ
          long_name: Surface runoff
          units: m/s
        - variable: hillslope_subsurface_runoff
          name: QSUB_LIQ
          long_name: Subsurface runoff
          units: m/s
        - variable: storage
          name: STORAGE_LIQ
          long_name: Mosart liquid storage
          units: m3
        - variable: runoff_land
          name: RIVER_DISCHARGE_OVER_LAND_LIQ
          long_name: Mosart river basin flow
          units: m3/s
        - variable: channel_inflow_upstream
          name: channel_inflow
          long_name: Mosart main channel inflow to grid cell
          units: m3/s
        - variable: reservoir_storage
          name: WRM_STORAGE
          long_name: Mosart storage in reservoir
          units: m3
        - variable: grid_cell_supply
          name: WRM_SUPPLY
          long_name: Mosart reservoir supply to grid cell
          units: m3/s
        - variable: grid_cell_demand_rate
          name: WRM_DEMAND0
          long_name: Mosart demand reqeusted by grid cell
          units: m3/s
        - variable: grid_cell_deficit
          name: WRM_DEFICIT
          long_name: Mosart unmet demand at grid cell
          units: m3
    # non time dependent fields to include in the output
    # note that latitude and longitude are automatically included as 'lat' and 'lon'
    grid_output:
        - variable: id
          name: GINDEX
          long_name: Index of the grid cell in a 1d array
        - variable: outlet_id
          name: OUTLETG
          long_name: Index of the outlet grid cell in a 1d array
        - variable: downstream_id
          name: DSIG
          long_name: Index of the downstream grid cell in a 1d array
        - variable: land_mask
          name: MASK
          long_name: Land mask 1=Land, 2=Ocean, 3=Outlet
        - variable: area
          name: area
          long_name: area
        - variable: total_drainage_area_multi
          name: areatotal
          long_name: areatotal
        - variable: total_drainage_area_single
          name: areatotal2
          long_name: areatotal2

### 
### Grid
###
grid:
    # path to the grid domain file; can be absolute or relative to the source code root
    path: ./input/domains/MOSART_NLDAS_8th_20160426.nc
    # longitude field name
    longitude: lon
    # latitude field name
    latitude: lat
    # variable field names
    variables:
        # fraction of unit draining to outlet field
        drainage_fraction: frac
        # local drainage area field name
        local_drainage_area: area
        # total upstream drainage area using concept of multi flow direction field name [m2]
        total_drainage_area_multi: areaTotal
        # total upstream drainage area using concept of single flow direction field name [m2]
        total_drainage_area_single: areaTotal2
        # grid cell id field name
        id: ID
        # downstream ID field name
        downstream_id: dnID
        # flow direction field name
        flow_direction: fdir
        # Manning roughness coefficient for overland flow field name
        hillslope_manning: nh
        # Manning's roughness coefficient for tributary channel flow
        subnetwork_manning: nt
        # Manning's roughness coefficient for main channel flow
        channel_manning: nr
        # topographic slope field name
        hillslope: hslp
        # drainage density field name [m^-1]
        drainage_density: gxr
        # mean tributary channel slope averaged through the unit field name
        subnetwork_slope:  tslp
        # bankfull width of local tributaries field name [m]
        subnetwork_width: twid
        # main channel length field name [m]
        channel_length: rlen
        # main channel slope field name
        channel_slope: rslp
        # bankfull width of main channel field name [m]
        channel_width: rwid
        # floodplain width linked to main channel field name [m]
        channel_floodplain_width: rwid0
        # bankfull depth of main channel field name [m]
        grid_channel_depth: rdep
    # land grid information
    # TODO this is just needed for land_frac, so should just add it to mosart grid
    # TODO assumed to be the same grid as the main grid
    land:
      # path to the land grid domain file; can be absolute or relative to the source code root
      path: ./input/domains/domain.lnd.nldas2_0224x0464_c110415.nc
      # land fraction field name
      land_fraction: frac
###
### Runoff (forcing input)
###
runoff:
    # flag to enable/disable reading runoff from file
    # if disabled, runoff variables should be provided by the model driver
    read_from_file: true
    # path to the runoff file; can be absolute or relative to the source code root
    path: ./input/runoff/Livneh_NLDAS_1980_1985.nc
    # longitude field name
    longitude: lon
    # latitude field name
    latitude: lat
    # time field name
    time: time
    # variables
    variables:
        # surface runoff [mm/s]
        surface_runoff: QOVER
        # subsurface runoff [mm/s]
        subsurface_runoff: QDRAI
        # wetland runoff [mm/s]
        wetland_runoff: ~

###
### Water Management (Demand and Reservoirs)
###
water_management:
    # flag to turn this feature on or off
    enabled: true
    # flag to enable or disable regulation
    regulation_enabled: true
    # flag to enable or disable extraction
    extraction_enabled: true
    # extraction from main channel
    extraction_main_channel_enabled: true
    # Demand
    demand:
        # flag to enable/disable reading demand from file
        # if disabled, demand should be provided by the model driver
        read_from_file: true
        # path to the demand file; can be absolute or relative to the source code root
        path: ./input/demand/RCP8.5_GCAM_water_demand_1980_1985.nc
        # longitude field name
        longitude: lon
        # latitude field name
        latitude: lat
        # time field name
        time: time
        # demand field name # TODO support the different demand types using the flags
        demand: totalDemand
        # TODO these aren't available yet
        # flag to enable or disable groundwater
        groundwater_enabled: false
        # flag to enable or disable return flow
        return_flow_enabled: false
        # flag to enable or disable the tracking of irrigation vs non irrigation demand
        total_demand_enabled: false
    # Reservoirs
    reservoirs:
        # path to the reservoir parameter file; can be absolute or relative to the source code root
        path: ./input/reservoirs/US_reservoir_8th_NLDAS3_updated_20200421.nc
        # longitude field name
        longitude: lon
        # latitude field name
        latitude: lat
        # streamflow field name [m3/s]
        streamflow: Qmon
        # streamflow time resolution - 'month' or 'epiweek'
        streamflow_time_resolution: month
        # demand field name [m3/s]
        demand: demand
        # demand time resolution - 'month' or 'epiweek'
        demand_time_resolution: month
        # grid id to reservoir id mapping field
        grid_to_reservoir: gridID_from_Dam
        # grid_to_reservoior reservoir id dimension
        grid_to_reservoir_reservoir_dimension: Dams
        # variable field names
        variables:
            # reservoir id field name - note that this is not an official id, just the identifier used elsewhere in the input
            reservoir_id: DamInd_2d
            # runoff capacity field name [m3 ??]
            reservoir_runoff_capacity: RUNOFF_CAP
            # height field name [m ??]
            reservoir_height: dam_hgt
            # length field name [m ??]
            reservoir_length: dam_len
            # surface area field name [km2]
            reservoir_surface_area: area_skm
            # storage capacity field name [km3]
            reservoir_storage_capacity: cap_mcm
            # depth field name [m]
            reservoir_depth: depth_m
            # use irrigation field name
            reservoir_use_irrigation: use_irri
            # use electricity field name
            reservoir_use_electricity: use_elec
            # use supply field name
            reservoir_use_supply: use_supp
            # use flood control field name
            reservoir_use_flood_control: use_fcon
            # use recreation field name
            reservoir_use_recreation: use_recr
            # use navigation field name
            reservoir_use_navigation: use_navi
            # use fish protection field name
            reservoir_use_fish_protection: use_fish
            # withdrawal field name
            reservoir_withdrawal: withdraw
            # conveyance field name
            reservoir_conveyance: conveyance

###
### Inundation
###
inundation:
    # flag to turn this feature on or off
    enabled: false

###
### Sediment
###
sediment:
    # flag to turn this feature on or off
    enabled: false

###
### Reservoir Stratification
###
reservoir_stratification:
    # flag to turn this feature on or off
    enabled: false

###
### Heat
###
heat:
    # flag to turn this feature on or off
    enabled: false
